CREATE USER dev_user WITH PASSWORD 'airflow';

CREATE DATABASE bronze;
GRANT ALL PRIVILEGES ON DATABASE bronze TO dev_user;

CREATE DATABASE silver;
GRANT ALL PRIVILEGES ON DATABASE silver TO dev_user;

CREATE DATABASE gold;
GRANT ALL PRIVILEGES ON DATABASE gold TO dev_user;